### ISSUE TITLE
Create file with certificate and private key combined (lighttpd)

### ISSUE THREAD

**Issue by kpcyrd** [kpcyrd/acme-redirect#8]
Lighttpd seems to prefer the certificate in this format. This currently requires scripting in the exec hooks.

**Comment by gstrauss** [comment]
> Lighttpd seems to prefer the certificate in this format. This currently requires scripting in the exec hooks.

That is outdated information.

lighttpd supports a separate file for key using `ssl.privkey` since lighttpd 1.4.53 (released Jan 2019), which is old enough to ship with Debian Buster.  Latest release of lighttpd is lighttpd 1.4.55, which is available in buster-backports.  Most major distros ship lighttpd 1.4.55.  I highlighted Debian since Debian and Ubuntu are among the slowest to pick up new releases.

lighttpd mod_openssl natively supports ALPN "acme-tls/1"
https://redmine.lighttpd.net/projects/lighttpd/wiki/HowToSimpleSSL
