### ISSUE TITLE
Global hooks, exec= in /etc/acme-redirect.conf

### ISSUE THREAD

**Issue by kpcyrd** [kpcyrd/acme-redirect#9]
Maintaining a list of exec hooks for every certificate can be tedious, instead we should have an extra list that applies to every certificate config in addition to individual configuration. Things like reloading nginx could qualify as a global hook.

**Comment by alerque** [comment]
Yes please! Literally every cert I have needs to trigger the same Apache reload. I'm also wondering if there is a way to setup Systemd to take care of this, something like a reload dependency where acme-redirect could signal it's own supervisor to trigger reload events on other services. Is that even possible?

**Comment by kpcyrd** [comment]
@alerque thanks for replying! Do you have an opinion on if the global setting should be a fallback, so only execute if there are no hooks for a certificate or should they execute in addition?

**Comment by alerque** [comment]
I would expect it to be a fallback such that the global setting was only used if no per-domain hook was set.

**Comment by kpcyrd** [comment]
@alerque btw, which distro are you on and do you use some kind of package or do you build from source? :)

**Comment by alerque** [comment]
I'm on Arch Linux and using the `[community]` package.

By the way I saw the `package()` shenanigans it takes to install this. I know Cargo is great as a Rust build tool but pretty terrible at setting up a whole package with other parts besides a single binary. I have some experience setting up Autotools (autoconf/automake) to play nice with Rust projects. If you're interested in that happening for this project so that distro packagers don't have to re-invent the wheel to get everything in the right places please feel free to open an issue for it and assign me. I'd be happy to contribute at least some working boilerplate to that end.

**Comment by kpcyrd** [comment]
Sorry for the late reply. I'd rather avoid autotools since I never really understood how it works. Most distros can probably copy from either the PKGBUILD or APKBUILD (depending on the init system) :)
